<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Base\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SB.PayrollManagement.Domain\SB.PayrollManagement.Domain.csproj" />
  </ItemGroup>

</Project>
